### ISSUE TITLE
mechanize operations breaking again

### ISSUE THREAD

**Issue by willettk** [willettk/rgz-analysis#33]
Trying to run an updated version the other day and the `mechanize` module returned errors again. The last portion of the error log's below. 

[example_500.txt](https://github.com/willettk/rgz-analysis/files/196264/example_500.txt)

Is this something we can skip over or restart for a specific file, @afgaron?

**Comment by afgaron** [comment]
It caught the error and handled to our specifications. Error code 500 is useless for debugging, unfortunately. Since it kept throwing the error, I think this was on CasJobs's end.

**Comment by willettk** [comment]
Could you explain the specifications (in words) in slightly more detail? I
thought we skipped a particular entry if it couldn't connect.

**Comment by afgaron** [comment]
Whenever it needs to download data from the web (CasJobs, Irsa, the RGZ JSON) and fails with one of the errors we've discussed before, it waits 10 seconds and tries again, After 5 failed attempts, the program terminates. I assumed the only reason CasJobs or Irsa would fail to return a response is if their server is down, in which case every entry would have the same problem. If the web-based JSON doesn't work, I check if it's just because that one isn't present; if so, I note that and move on, otherwise it's a server error. Your changes to having them downloaded should bypass that entirely.

**Comment by willettk** [comment]
Thanks - that's clearer. Guess I'll try running it again in `update` mode and we'll see if the SDSS servers (which were the problem yesterday) work this time.

**Comment by willettk** [comment]
Worked this time around (without changing any of the code), so it was likely something on the CasJobs or IRSA end. Good reminder to run this more often so that we don't have to wait overnight to see if things are synced.
